language: python

python:
  - "2.7"

env:
  - DJANGO=1.7.4

before_intall:
  - cp settings_travis.py settings.py

install:
  - pip install -q Django==$DJANGO

script:
  - python manage.py migrate
  - python manage.py test