language: python

python:
  - "2.7"

env:
  - DJANGO=1.7.4
  - DJANGO=1.4

install:
  - pip install -q Django==$DJANGO
  - pip install coveralls

script:
  - coverage run manage.py test
after_success:
  - coveralls