language: python

python:
  - "2.7"

env:
  - DJANGO=1.7.3
  - DJANGO=1.4

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - python setup.py test